# @name login
POST http://localhost:8000/login
Content-Type: application/json

{
  "username":"admin",
  "password":"123456"
}

//Agregar autos

###
POST http://127.0.0.1:8000/auto/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "nombre" : "max",
  "anio" : "1900",
  "fabricadeauto": { 
    
    "nombre": "chevrolett"
  }
}

###
POST http://127.0.0.1:8000/auto/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "nombre" : "camry",
  "anio" : "1900",
  "fabricadeauto": { 
    
    "nombre": "toyota"
  }
}

###
POST http://127.0.0.1:8000/auto/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "nombre" : "mustang",
  "anio" : "1900",
  "fabricadeauto": { 
    
    "nombre": "ford"
  }
}

###
POST http://127.0.0.1:8000/auto/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "nombre" : "leaf",
  "anio" : "1900",
  "fabricadeauto": { 
    
    "nombre": "Nissan"
  }
}

###
POST http://127.0.0.1:8000/auto/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "nombre" : "max",
  "anio" : "1900",
  "fabricadeauto": { 
   
    "nombre": "chevrolett"
  }
}


###
PUT http://127.0.0.1:8000/auto/2
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "nombre" : "carrio",
  "anio" : "2002",
}

###
POST http://127.0.0.1:8000/fabrica/
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

  {
    "id": "2",
    "nombre": "chevrolet"
  }
###

PUT http://127.0.0.1:8000/fabrica/2
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

  {
  
    "nombre": "fiat"
  }


